//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caesar.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Caesar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на я
        ///не
        ///что
        ///в
        ///и
        ///ты
        ///это
        ///на
        ///с
        ///он
        ///вы
        ///да
        ///как
        ///мы
        ///мне
        ///а
        ///меня
        ///у
        ///нет
        ///так
        ///но
        ///то
        ///все
        ///его
        ///тебя
        ///за
        ///о
        ///она
        ///тебе
        ///если
        ///они
        ///бы
        ///же
        ///ну
        ///здесь
        ///к
        ///из
        ///есть
        ///чтобы
        ///для
        ///хорошо
        ///когда
        ///по
        ///вас
        ///только
        ///вот
        ///просто
        ///был
        ///знаю
        ///нас
        ///было
        ///от
        ///всё
        ///может
        ///кто
        ///вам
        ///их
        ///очень
        ///там
        ///будет
        ///быть
        ///почему
        ///уже
        ///еще
        ///где
        ///спасибо
        ///или
        ///могу
        ///ничего
        ///сейчас
        ///хочу
        ///нам
        ///чем
        ///мой
        ///этого
        ///до
        ///ее
        ///теперь
        ///надо
        ///давай
        ///знаешь
        ///нужно
        ///больше
        ///этом
        ///нибудь
        ///была
        ///со
        ///раз
        ///ладно
        ///этот
        ///ему
        ///эй
        ///ли
        ///время
        ///даже
        ///дума [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string RUS {
            get {
                return ResourceManager.GetString("RUS", resourceCulture);
            }
        }
    }
}
